version: "3.8"

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"

  ngrok:
    image: wernight/ngrok:latest
    command: ngrok http sonarqube:9000
    depends_on:
      - sonarqube
