version: '3.4'

services:
  gamifywork.api:
    image: ${DOCKER_REGISTRY-}gamifyworkapi
    build:
      context: .
      dockerfile: src/GamifyWork.API/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Example@2023#
      MYSQL_DATABASE: gamifywork
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
