name: Full Stack Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore backend dependencies
        run: dotnet restore ./Application/Backend/GamifyWork/GamifyWork.sln
        working-directory: ./Application/Backend/GamifyWork

      - name: Build backend
        run: dotnet build -c Release --no-restore ./Application/Backend/GamifyWork/GamifyWork.sln
        working-directory: ./Application/Backend/GamifyWork

      - name: Run backend UnitTests
        run: dotnet test ./Application/Backend/GamifyWork/GamifyWork.sln
        working-directory: ./Application/Backend/GamifyWork

  ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Run frontend unit tests
        run: yarn test
        working-directory: ./Application/Frontend/GamifyWork

      - name: Start frontend development server
        run: yarn dev
        working-directory: ./Application/Frontend/GamifyWork
        background: true

      - name: Wait for frontend server to start
        run: sleep 10

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies for e2e
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Run Cypress e2e tests 🌊
        run: yarn cypress run
        working-directory: ./Application/Frontend/GamifyWork
