name: Full Stack Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore backend dependencies
        run: dotnet restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Build backend
        run: dotnet build -c Release --no-restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Run backend UnitTests
        run: dotnet test ./Application/Backend/GamifyWork/GamifyWork.sln

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Run frontend unit tests
        run: yarn test
        working-directory: ./Application/Frontend/GamifyWork

      - name: Start frontend development server
        run: nohup yarn dev &
        working-directory: ./Application/Frontend/GamifyWork

      - name: Wait for frontend server to start
        run: sleep 10

  keycloak:
    needs: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Keycloak Docker image
        run: docker pull rowanbattles/keywork

      - name: Run Keycloak Docker container
        run: docker run -d -p 8080:8080 rowanbattles/keywork


  End-to-end_tests:
    needs: keycloak
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            working-directory: ./Application/Frontend/GamifyWork

