name: Full Stack Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore backend dependencies
        run: dotnet restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Build backend
        run: dotnet build -c Release --no-restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Run backend UnitTests
        run: dotnet test ./Application/Backend/GamifyWork/GamifyWork.sln

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Restore frontend dependencies
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Build frontend
        run: yarn build
        working-directory: ./Application/Frontend/GamifyWork

      - name: Upload production-ready frontend files
        uses: actions/upload-artifact@v2
        with:
          name: frontend-files
          path: ./Application/Frontend/GamifyWork/dist

