name: Full Stack Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  api:
    runs-on: ubuntu-latest
    working-directory: ./Application/Backend/GamifyWork

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore backend dependencies
        run: dotnet restore ./GamifyWork.sln

      - name: Build backend
        run: dotnet build -c Release --no-restore ./GamifyWork.sln

      - name: Run backend UnitTests
        run: dotnet test ./GamifyWork.sln

  ui:
    runs-on: ubuntu-latest
    working-directory: ./Application/Frontend/GamifyWork

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies
        run: yarn install

      - name: Run frontend unit tests
        run: yarn test

      - name: Start frontend development server
        run: yarn dev
        background: true

      - name: Wait for frontend server to start
        run: sleep 10

  e2e:
    runs-on: ubuntu-latest
    working-directory: ./Application/Frontend/GamifyWork

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies for e2e
        run: yarn install

      - name: Run Cypress e2e tests 🌊
        run: yarn cypress run
