name: Full Stack Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore backend dependencies
        run: dotnet restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Build backend
        run: dotnet build -c Release --no-restore ./Application/Backend/GamifyWork/GamifyWork.sln

      - name: Run backend UnitTests
        run: dotnet test ./Application/Backend/GamifyWork/GamifyWork.sln

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore frontend dependencies
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Run frontend unit tests
        run: yarn test
        working-directory: ./Application/Frontend/GamifyWork

      - name: Start frontend development server
        run: nohup yarn dev &
        working-directory: ./Application/Frontend/GamifyWork

      - name: Wait for frontend server to start
        run: sleep 10

  End-to-end_tests:
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: yarn install
        working-directory: ./Application/Frontend/GamifyWork

      - name: Build frontend
        run: yarn dev &
        working-directory: ./Application/Frontend/GamifyWork

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER

      - name: Build and run Docker container
        run: |
          docker build -t gamify-work .
          docker run -d -p 5173:5173 -p 8080:8080 --name gamify-container gamify-work

      - name: Wait for frontend server to start
        run: |
          timeout=300
          while [ $timeout -gt 0 ]; do
            if nc -z localhost 5173; then
              break
            fi
            sleep 1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            echo "Timeout waiting for frontend server to start"
            exit 1
          fi

      - name: Wait for Keycloak server to start
        run: |
          timeout=300
          while [ $timeout -gt 0 ]; do
            if docker exec gamify-container curl -s -o /dev/null http://localhost:8080; then
              break
            fi
            sleep 1
            ((timeout--))
          done
          if [ $timeout -eq 0 ]; then
            echo "Timeout waiting for Keycloak server to start"
            exit 1
          fi

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Application/Frontend/GamifyWork




