name: SonarQube analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: dotnet tool install --global dotnet-sonarscanner --version 5.14.0

      - name: Verify SonarScanner Installation
        run: |
          if (Test-Path -Path .\.sonar\scanner\dotnet-sonarscanner) {
            Write-Output "SonarScanner for .NET is installed."
          } else {
            Write-Output "SonarScanner for .NET is not installed or the path is incorrect."
          }

      - name: Build and analyze
        shell: powershell
        run: |
          Set-Location -Path ./Application/Backend/GamifyWork/src/GamifyWork.API
          C:\Users\rowan\.dotnet\tools begin /k:"GamifyWork" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          C:\Users\rowan\.dotnet\tools end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
