name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner --version 5.14.0

      - name: Install dotnet-coverage
        run: dotnet tool install -g dotnet-coverage

      - name: Run SonarQube Analysis
        working-directory: ./Application/Backend/GamifyWork
        run: |
          dotnet sonarscanner begin /k:"GamifyWork" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.coverage.exclusions="**/Program.cs,**/dbContext.cs"
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  sonarqube-analysis-frontend:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Restore dependencies
        run: |
          yarn install
          npm install vitest
        working-directory: ./Application/Frontend/GamifyWork

      - name: Test and coverage
        run: yarn test --coverage
        working-directory: ./Application/Frontend/GamifyWork

      - name: Remove lcov-report Directory
        run: rm -rf ./Application/Frontend/GamifyWork/coverage/lcov-report

      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./Application/Frontend/GamifyWork
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REACT }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
