name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker://docker
        with:
          args: |
            run -d --name sonarqube -p 9000:9000 sonarqube

      - name: Set up ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Start ngrok
        run: |
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok http 9000 & sleep 5
          export NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)

      - name: Export ngrok URL
        run: echo "NGROK_URL=${{ env.NGROK_URL }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Run SonarQube Analysis
        working-directory: ./Application/Backend/GamifyWork
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.14.0
          dotnet sonarscanner begin /k:"GamifyWork" /d:sonar.host.url="${{ env.NGROK_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
